spring:
  config:
    import:
      - classpath:/config-common-${spring.profiles.active}.yml
      - classpath:/config-data-${spring.profiles.active}.yml

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev